import { AztecDocPage } from '@/components/landing/AztecDocPage';

export default function TermsPage() {
  return (
    <AztecDocPage
      eyebrow="Compliance · Terms of Operation"
      title="Protocol Interaction Agreement"
      subtitle="These Terms of Operation govern your access to and use of the Humanity Ledger protocol, including the humanidfi.com web application, the Ledger Chat communications layer, the Aztec L2 private state execution environment, and all associated relay infrastructure. By generating a cryptographic keypair and interacting with the protocol, you enter into a binding agreement with Humanity Ledger on the terms set out below."
      sections={[
        {
          id: 'definitions',
          title: '1. Definitions',
          paragraphs: [
            'In these Terms of Operation, the following definitions apply.',
            '"Protocol" means the Humanity Ledger cryptographic protocol, comprising the Aztec L2 smart contracts, the Noir zero-knowledge circuits, the XMTP relay integration, and the Ledger Chat application layer collectively.',
            '"User" means any natural person or legal entity that generates a cryptographic keypair and initiates any interaction with the Protocol.',
            '"Private State" means the encrypted UTXO commitments, nullifiers, and associated proof artifacts held within the Aztec L2 shielded pool that represent a User\'s assets and protocol state.',
            '"Proof" means a zk-SNARK generated by the user\'s local Private Execution Environment (PXE) attesting to the validity of a proposed state transition.',
            '"QDs" or "Quantum Dots" means the native utility token of the Protocol, issued as a Noir smart contract natively deployed on Aztec L2, governed by the economic parameters defined in the Protocol specification.',
            '"Relay" means the XMTP-based decentralized message relay network used to transmit encrypted communication payloads between protocol participants.',
          ],
        },
        {
          id: 'eligibility',
          title: '2. Eligibility and Capacity',
          paragraphs: [
            'Access to the Protocol is restricted to persons who have reached the age of legal majority in their jurisdiction of residence and who have full legal capacity to enter into binding agreements. By accessing the Protocol, you represent and warrant that you meet these eligibility requirements.',
            'The Protocol is not available to Persons designated on any applicable sanctions list, including lists maintained by the United Nations Security Council, the European Union, His Majesty\'s Treasury, the US Office of Foreign Assets Control (OFAC), or any other applicable governmental body. You represent and warrant that you are not such a Person and that your use of the Protocol does not violate any applicable sanctions regime.',
            'If you are accessing the Protocol on behalf of a legal entity, you represent and warrant that you have authority to bind that entity to these Terms of Operation.',
          ],
        },
        {
          id: 'cryptographic-liability',
          title: '3. Cryptographic Liability and Key Custody',
          paragraphs: [
            'The Protocol is a non-custodial, cryptographic system. Humanity Ledger holds no private keys, no custody over user assets, and exercises no control over any state transition once a valid Proof has been submitted to the Aztec sequencer. By interacting with the Protocol, you irrevocably accept sole and exclusive responsibility for the security of your private keys, seed phrases, hardware authentication modules, and all derivative credentials.',
            'You acknowledge that the loss, theft, destruction, or compromise of your private keys will result in the permanent and irrecoverable loss of access to any Private State associated with those keys. Humanity Ledger has no technical mechanism to recover lost keys, restore inaccessible Private State, or reverse any on-chain state transition. This limitation is a mathematical property of the cryptographic system, not an operational policy.',
            'You are solely responsible for maintaining adequate backups of your key material in accordance with cryptographic security best practices, including the use of hardware security modules, geographically distributed secret shares, and verified recovery procedures.',
          ],
          bullets: [
            'Hardware security: We strongly recommend using hardware-backed key storage (Apple Secure Enclave, Android StrongBox, or a hardware security key) for all private key operations.',
            'Seed phrase custody: If your wallet implementation uses a BIP-39 seed phrase, store it offline, in multiple geographically separated locations, protected against physical access by third parties.',
            'No recovery mechanism: Humanity Ledger cannot and will not implement any key recovery mechanism, as doing so would compromise the non-custodial security model of the Protocol.',
          ],
        },
        {
          id: 'protocol-operations',
          title: '4. Permitted and Prohibited Protocol Operations',
          paragraphs: [
            'You may use the Protocol for any lawful purpose consistent with these Terms and applicable law. Permitted uses include: private asset transfers within the Aztec L2 shielded pool, encrypted peer-to-peer communications via Ledger Chat, participation in Protocol governance, and building third-party applications that integrate with the Protocol via the public API.',
            'The following uses are expressly prohibited. This list is non-exhaustive. Prohibited uses include: using the Protocol to facilitate money laundering, terrorist financing, or any transaction that violates applicable AML/CFT regulations; submitting Proofs that contain fraudulent public inputs; operating systematic denial-of-service attacks against relay infrastructure; and using the Protocol to transmit communications that are unlawful, harassing, defamatory, or that infringe third-party intellectual property rights.',
            'Violation of these prohibitions may result in the blocking of your API access and may be reported to relevant law enforcement authorities. We note that by the nature of the Protocol, we cannot prevent all prohibited uses, but we will take all technically feasible and legally required steps to address identified violations.',
          ],
        },
        {
          id: 'code-as-law',
          title: '5. Code as Law: Supremacy of the Smart Contract',
          paragraphs: [
            'The Humanity Ledger Protocol is governed by Noir smart contracts deployed on the Aztec L2 network. These contracts define the rules of the Protocol with mathematical precision. To the extent of any inconsistency between the human-readable provisions of these Terms of Operation and the compiled bytecode of the deployed smart contracts, the bytecode governs.',
            'This principle, commonly known as "Code as Law" in the blockchain context, reflects the fundamental nature of a decentralized protocol: the code is the agreement, and the code executes autonomously without discretion. No representative of Humanity Ledger has authority to waive, modify, or suspend the execution of any smart contract function.',
            'Smart contract upgrades and parameter changes are governed by the Protocol\'s governance mechanism, which requires cryptographic participation from verified protocol participants. We commit to providing advance notice of proposed upgrades through the Protocol changelog.',
          ],
        },
        {
          id: 'financial-regulation',
          title: '6. Financial Regulation and MiCA Compliance',
          paragraphs: [
            'QDs (Quantum Dots) are utility tokens as defined under Article 3(1)(5) of Regulation (EU) 2023/1114 (MiCA). They are not e-money tokens, asset-referenced tokens, or financial instruments as defined under applicable EU financial regulation. Their primary function is to provide access to protocol features, facilitate governance participation, and settle network fees.',
            'Humanity Ledger is in the process of completing the notification procedures applicable to utility token issuers under MiCA, in coordination with the relevant competent authority. The Token Generation Event will not proceed until all applicable regulatory requirements have been satisfied.',
            'Nothing in the Protocol, these Terms, or any communication from Humanity Ledger constitutes financial advice, investment advice, or a recommendation to acquire, hold, or dispose of any cryptographic asset. Interacting with the Protocol involves significant risks, including the risk of total loss of any value associated with your Private State. You should obtain independent financial and legal advice before participating.',
          ],
          bullets: [
            'QDs are utility tokens under MiCA Article 3(1)(5) — not securities, e-money, or financial instruments.',
            'The Protocol does not accept fiat currency deposits and does not hold client assets.',
            'Past performance of cryptographic assets is not indicative of future results.',
            'You bear all market, liquidity, regulatory, and technical risks associated with your use of the Protocol.',
          ],
        },
        {
          id: 'limitation-of-liability',
          title: '7. Limitation of Liability',
          paragraphs: [
            'To the maximum extent permitted by applicable law, Humanity Ledger, its directors, officers, employees, contractors, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of assets, loss of data, business interruption, or loss of anticipated savings, arising from or in connection with your use of the Protocol.',
            'Our aggregate liability to you for direct damages shall not exceed the greater of: (a) the total fees you have paid to Humanity Ledger in the twelve months preceding the claim; or (b) one hundred euros (EUR 100).',
            'These limitations apply regardless of the legal theory under which a claim is brought and regardless of whether Humanity Ledger has been advised of the possibility of such damages. Some jurisdictions do not permit the exclusion or limitation of certain categories of liability; in such cases, our liability is limited to the minimum extent permitted by applicable law.',
          ],
        },
        {
          id: 'governing-law',
          title: '8. Governing Law and Dispute Resolution',
          paragraphs: [
            'These Terms of Operation are governed by the laws of Romania, without regard to its conflict of laws provisions. You agree to submit to the exclusive jurisdiction of the courts of Romania for the resolution of any dispute arising out of or in connection with these Terms.',
            'Notwithstanding the foregoing, nothing in these Terms prevents either party from seeking urgent injunctive or other interim relief from any court of competent jurisdiction to prevent irreparable harm pending the outcome of formal proceedings.',
            'For consumers resident in the European Union, mandatory statutory consumer protections applicable under the law of your country of residence are not affected by the choice of governing law in these Terms.',
          ],
        },
        {
          id: 'contact-legal',
          title: '9. Contact for Legal Matters',
          paragraphs: [
            'For all legal enquiries, compliance matters, and formal notices, contact Humanity Ledger at: humanityledger@icloud.com',
            'These Terms of Operation were last reviewed on 28 September 2026. We reserve the right to update these Terms at any time. Material updates will be communicated via the protocol changelog with a minimum notice period of 14 days before the new terms take effect for existing users.',
          ],
          callout: {
            title: 'Legal Notices',
            body: 'For formal legal correspondence, regulatory enquiries, and compliance matters, direct all communications to our legal team. We commit to acknowledging all formal notices within 72 hours.',
            href: 'mailto:humanityledger@icloud.com',
            hrefLabel: 'Contact Legal Team',
          },
        },
      ]}
    />
  );
}
