import { AztecDocPage } from '@/components/landing/AztecDocPage';

export default function DevelopersPage() {
  return (
    <AztecDocPage
      eyebrow="Developers · Protocol Engineering"
      title="Developer Documentation"
      subtitle="The complete technical reference for building on the Humanity Ledger protocol. From Zero-Knowledge circuit design in Noir to XMTP relay integration and smart contract deployment on Aztec, everything you need to build sovereign cryptographic applications."
      sections={[
        {
          id: 'architecture-overview',
          title: 'Protocol Architecture Overview',
          paragraphs: [
            'Humanity Ledger is a multi-layer cryptographic protocol composed of three distinct execution environments that work in concert. Understanding the boundary between each layer is essential before integrating.',
            'The first layer is the Aztec L2 ZK-Rollup, responsible for all private financial state transitions. It compiles Noir circuits into UltraPlonk zero-knowledge proofs, which are then recursively verified and settled on Ethereum L1 via the Aztec sequencer network.',
            'The second layer is the XMTP Decentralised Relay, an independent gossip network built on the Waku v2 protocol. It handles all ephemeral message routing and peer discovery for Ledger Chat and the WebRTC call signalling system. The relay is entirely blind to the content it routes.',
            'The third layer is the Client-Side Private Execution Environment (PXE). This is a WASM binary that runs inside the user browser and is responsible for all local proof generation, key derivation, and transaction construction. No private data ever leaves the PXE.',
          ],
          callout: {
            title: 'Core Principle',
            body: 'The protocol is designed such that the Humanity Ledger operator infrastructure has zero cryptographic capability to read user state, decrypt messages, or identify participants. This is enforced mathematically, not by policy.',
          },
        },
        {
          id: 'network-config',
          title: 'Network Configuration',
          paragraphs: [
            'All SDK integrations must begin by importing and validating the protocol configuration constants. These values are pinned to the currently deployed contract addresses on the Aztec Sepolia testnet and will be updated when Mainnet is live.',
          ],
          bullets: [
            'chainId: 31337 (Aztec Sandbox) / 11155111 (Sepolia Testnet)',
            'proofSystem: barretenberg-ultraplonk',
            'curve: BN254 (Grumpkin for EC operations inside circuits)',
            'XMTP Environment: production (mainnet) or dev (testnet)',
          ],
        },
        {
          id: 'noir-identity-circuit',
          title: 'ZK Identity Circuit (Noir)',
          paragraphs: [
            'The foundational circuit of the Humanity Ledger protocol is the hardware enclave verification circuit. It is written in the Noir domain-specific language and compiled by the Barretenberg backend into a UltraPlonk proof.',
            'The circuit enforces two mathematical constraints simultaneously. First, it verifies that an ECDSA P-256 signature was produced by a private key resident in a hardware Secure Enclave (the prover knows the signature without ever transmitting the private key). Second, it computes a deterministic Poseidon hash of the enclave public key coordinates and asserts it equals the submitted identity nullifier, preventing replay attacks.',
            'Example circuit (Noir):',
          ],
          callout: {
            title: 'Noir Circuit: verify_hardware_enclave',
            body: [
              'use dep::std;',
              'use dep::aztec::context::PrivateContext;',
              '',
              'fn verify_hardware_enclave(',
              '    pub_key_x: pub Field,',
              '    pub_key_y: pub Field,',
              '    signature: [u8; 64],',
              '    message_hash: [u8; 32],',
              '    identity_nullifier: pub Field',
              ') {',
              '    let valid = std::ecdsa_secp256k1::verify_signature(',
              '        pub_key_x, pub_key_y, signature, message_hash',
              '    );',
              '    assert(valid);',
              '',
              '    let computed_nullifier = std::hash::poseidon::bn254::hash_2([',
              '        pub_key_x, pub_key_y',
              '    ]);',
              '    assert(identity_nullifier == computed_nullifier);',
              '}',
            ].join('\n'),
          },
        },
        {
          id: 'xmtp-integration',
          title: 'XMTP Relay Integration',
          paragraphs: [
            'Ledger Chat uses the XMTP browser SDK v5.3.0. The client is initialized once per wallet session and stored in a singleton registry. All messages are end-to-end encrypted using the Double Ratchet Algorithm over X25519 elliptic curves before being submitted to the relay.',
            'The critical implementation detail is that XMTP v5.3.0 requires EIP-55 checksummed Ethereum addresses as identifiers. Lowercase or unchecksummed addresses will silently create separate conversation threads, meaning the recipient will never receive the message. Always use viem getAddress() to normalise before any XMTP call.',
            'Streaming all incoming messages in real time:',
          ],
          callout: {
            title: 'TypeScript: XMTP Stream Setup',
            body: [
              "import { Client } from '@xmtp/browser-sdk';",
              "import { getAddress } from 'viem';",
              '',
              'async function* streamMessages(client: Client, signal?: AbortSignal) {',
              '  await client.conversations.sync();',
              '  const stream = await client.conversations.streamAllMessages();',
              '',
              '  try {',
              '    for await (const message of stream) {',
              '      if (signal?.aborted) break;',
              '      yield message;',
              '    }',
              '  } finally {',
              '    if (typeof (stream as any).return === "function") {',
              '      (stream as any).return();',
              '    }',
              '  }',
              '}',
            ].join('\n'),
          },
        },
        {
          id: 'send-message',
          title: 'Sending Encrypted Messages',
          paragraphs: [
            'Sending a message requires constructing a DM conversation object via newDmWithIdentifier. This call is idempotent: if the conversation already exists on the XMTP network, it returns the existing object. If not, it creates a new encrypted channel.',
            'The address passed to newDmWithIdentifier must be EIP-55 checksummed. The function below includes a three-attempt retry with exponential backoff (1s, 2s) and automatic fallback to the offline queue if the recipient is not yet registered on the XMTP network.',
          ],
          callout: {
            title: 'TypeScript: sendMessage with Offline Queue Fallback',
            body: [
              "import { getAddress } from 'viem';",
              '',
              'async function sendMessage(',
              '  client: Client,',
              '  toAddress: string,',
              '  content: string,',
              '  senderEthAddress: string',
              '): Promise<void> {',
              '  const normalizedTo = getAddress(toAddress);',
              '  const identifier = { identifier: normalizedTo, identifierKind: "Ethereum" };',
              '',
              '  for (let i = 0; i < 3; i++) {',
              '    try {',
              '      const dm = await client.conversations.newDmWithIdentifier(identifier);',
              '      await dm.send(content);',
              '      await dm.sync().catch(() => {});',
              '      return;',
              '    } catch (err: any) {',
              '      const msg = err?.message?.toLowerCase() ?? "";',
              '      if (msg.includes("not on xmtp") || msg.includes("no inbox")) break;',
              '      if (i < 2) await new Promise(r => setTimeout(r, 1000 * Math.pow(2, i)));',
              '    }',
              '  }',
              '',
              '  // Offline queue fallback',
              "  await fetch('/api/chat/queue', {",
              '    method: "POST",',
              '    headers: { "Content-Type": "application/json", "x-web3-address": senderEthAddress },',
              '    body: JSON.stringify({ sender: senderEthAddress, recipient: toAddress, content }),',
              '  });',
              '}',
            ].join('\n'),
          },
        },
        {
          id: 'zk-transfer',
          title: 'Zero-Knowledge Asset Transfers',
          paragraphs: [
            'Quantum Dot (QD) transfers are compiled into zero-knowledge proofs locally inside the PXE WASM module. The transaction never exposes the sender identity, the recipient identity, or the transfer amount to any observer.',
            'The transfer constructs a new encrypted UTXO commitment for the recipient and a nullifier hash for the spent UTXO of the sender. Both are submitted to the Aztec sequencer, which batches them into a rollup block and settles the recursive proof on Ethereum L1.',
          ],
          callout: {
            title: 'TypeScript: QD Transfer via PXE',
            body: [
              "import { createPXEClient, Fr, AztecAddress, AccountWallet } from '@aztec/aztec.js';",
              "import { QDSTokenContract } from '@/contracts/QDSToken';",
              '',
              'async function transferQDs(',
              '  wallet: AccountWallet,',
              '  recipientAztecAddress: string,',
              '  amount: bigint',
              '): Promise<void> {',
              '  const pxe = createPXEClient(process.env.NEXT_PUBLIC_AZTEC_PXE_URL!);',
              '  const token = await QDSTokenContract.at(',
              '    AztecAddress.fromString(process.env.NEXT_PUBLIC_QDS_CONTRACT_ADDRESS!),',
              '    wallet',
              '  );',
              '',
              '  const recipient = AztecAddress.fromString(recipientAztecAddress);',
              '',
              '  await token.methods',
              '    .transfer(recipient, new Fr(amount))',
              '    .send()',
              '    .wait();',
              '}',
            ].join('\n'),
          },
        },
        {
          id: 'webauthn-identity',
          title: 'Hardware-Rooted Identity (WebAuthn)',
          paragraphs: [
            'The Humanity Ledger identity system anchors trust in hardware Secure Enclaves via the WebAuthn API (FIDO2). The enclave generates an ECDSA P-256 keypair that is physically fused into the device silicon and can never be extracted by software, operating systems, or the Humanity Ledger protocol itself.',
            'Registration creates a new credential in the Secure Enclave and returns the public key and a credential ID. Authentication produces an ECDSA signature over a server-issued challenge, which is then fed into the Noir verification circuit described above to generate a zero-knowledge proof of hardware-rooted identity.',
          ],
          bullets: [
            'Supported authenticators: Apple Secure Enclave (FaceID/TouchID), Android StrongBox/TEE, FIDO2 Hardware Keys (YubiKey).',
            'Algorithm: ES256 (ECDSA with SHA-256 over P-256 curve).',
            'Attestation: Self-attestation for privacy. No attestation certificate is transmitted to the server.',
            'The server stores only the public key and credential ID, never any private keying material.',
          ],
        },
        {
          id: 'api-reference',
          title: 'REST API Reference',
          paragraphs: [
            'The Humanity Ledger backend exposes a set of authenticated REST endpoints for contact management, offline message queuing, and notification delivery. All endpoints that modify state require either a server-side session cookie or the x-web3-address header for wallet-connected users.',
          ],
          bullets: [
            'POST /api/chat/queue — Queue an encrypted message for an offline recipient. Body: { sender, recipient, content }. Content max 4096 characters.',
            'GET /api/chat/pending?address={addr} — Retrieve pending messages for a wallet address. Requires x-web3-address header matching the address parameter.',
            'DELETE /api/chat/pending?address={addr}&peer={peer} — Consume and delete delivered pending messages from a specific peer.',
            'POST /api/chat/contacts/request — Send a contact request. Body: { toAddress }. Deduplication enforced: only one pending request allowed per pair.',
            'GET /api/chat/contacts/request?direction=incoming|outgoing — List pending contact requests with enriched user profile data.',
            'POST /api/chat/contacts/request/{action} — Accept or reject a contact request by ID. Actions: accept, reject.',
            'POST /api/chat/report — Submit a user report. Body: { reporter, reported, reason }.',
          ],
          callout: {
            title: 'Authentication',
            body: 'All API endpoints support three authentication mechanisms in priority order: (1) x-verified-session-address header injected by middleware after cryptographic JWT verification (cannot be forged), (2) server-side NextAuth session cookie, (3) x-web3-address header for WalletConnect-only sessions (trusted for non-sensitive reads).',
          },
        },
        {
          id: 'smart-contracts',
          title: 'Smart Contract Architecture',
          paragraphs: [
            'The Humanity Ledger protocol is governed by three core smart contracts deployed on the Aztec L2 network. All contracts are written in Noir and compiled to verifiable bytecode by the Barretenberg prover.',
            'QDSToken.nr is the native Quantum Dot asset contract. It implements a UTXO-based private balance model using Aztec note architecture. All transfer operations are shielded: senders, recipients, and amounts are provably hidden from all observers including the Aztec sequencer.',
            'ZKIdentityRegistry.nr is the Sybil resistance contract. It stores the Merkle tree of registered hardware enclave public key commitments. Identity registration, nullifier publication, and social recovery guardian updates are all performed via zero-knowledge proofs.',
            'StudioProvenance.nr manages cryptographic provenance records for the AI Studio component, enabling tamper-evident attribution of generated content to specific verified human identities without revealing the identity itself.',
          ],
          callout: {
            title: 'Audit Status',
            body: 'All three contracts are currently undergoing formal cryptographic audit. Results will be published at /docs/audits upon completion. The codebase is open-source and available for public review on GitHub.',
            href: '/docs/audits',
            hrefLabel: 'View Audit Reports',
          },
        },
        {
          id: 'sdk-quickstart',
          title: 'SDK Quick Start',
          paragraphs: [
            'The Humanity Ledger SDK is designed to be integrated into any Next.js, React, or Node.js application in under ten minutes. The package bundles the XMTP browser client, the Aztec PXE WASM, and all Humanity Ledger-specific cryptographic utilities.',
          ],
          bullets: [
            'Step 1 — Install: npm install @humanity-ledger/sdk @xmtp/browser-sdk @aztec/aztec.js',
            'Step 2 — Initialise the XMTP client: use getXMTPClient(wagmiSigner) from @humanity-ledger/sdk.',
            'Step 3 — Connect the Aztec PXE: use createPXEClient(pxeUrl) from @aztec/aztec.js.',
            'Step 4 — Register identity: submit the WebAuthn credential to the ZKIdentityRegistry contract via the PXE.',
            'Step 5 — Start streaming messages: use streamMessages(client, abortSignal) and iterate with for await.',
          ],
          callout: {
            title: 'Environment Variables Required',
            body: [
              'NEXT_PUBLIC_XMTP_ENV=production',
              'NEXT_PUBLIC_AZTEC_PXE_URL=https://aztec-pxe.humanidfi.com',
              'NEXT_PUBLIC_QDS_CONTRACT_ADDRESS=0x...',
              'NEXT_PUBLIC_ZK_REGISTRY_ADDRESS=0x...',
              'DATABASE_URL=postgresql://...',
            ].join('\n'),
          },
        },
      ]}
    />
  );
}
